# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.BigIntegerField()),
                ('nome_fantasia', models.TextField()),
                ('razao_social', models.TextField()),
                ('inscri_municipal', models.TextField(null=True)),
                ('inscri_estadual', models.TextField(null=True)),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem', models.DecimalField(decimal_places=2, max_digits=4)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telefone1', models.TextField(null=True)),
                ('telefone2', models.TextField(null=True)),
                ('celular1', models.TextField(null=True)),
                ('celular2', models.TextField(null=True)),
                ('site', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.TextField(null=True)),
                ('numero', models.TextField(null=True)),
                ('referencia', models.TextField(null=True)),
                ('cep', models.BigIntegerField(null=True)),
                ('bairro', models.TextField(null=True)),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uf', models.CharField(max_length=2)),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('desconto_porcentagem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField()),
                ('total_faturado', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('desconto_geral_porcent', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('desconto_geral_valor', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Prazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('preco1', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('preco2', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('preco3', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Representacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.BigIntegerField(null=True)),
                ('nome_fantasia', models.TextField()),
                ('razao_social', models.TextField()),
                ('inscri_estadual', models.TextField(null=True)),
                ('contato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Contato')),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VendedorDoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contato')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='representacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Representacao'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='prazo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Prazo'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='representacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Representacao'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TipoPedido'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Produto'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Estado'),
        ),
        migrations.AddField(
            model_name='comissao',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Pedido'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Contato'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Endereco'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estado'),
        ),
    ]
